build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true

complexity:
  LongMethod:
    threshold: 60

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
